---
- name: Get all release directory names
  find:
    paths: "{{ project_root }}/releases"
    file_type: directory
  register: release_dirs
  ignore_errors: true

- name: Extract release folder names
  set_fact:
    releases_array: "{{ release_dirs.files | default([]) | map(attribute='path') | map('basename') | list }}"

- name: Set default releases_array if empty
  set_fact:
    releases_array: [ "00000000000000" ]
  when: releases_array is not defined or releases_array | length == 0


- name: Get current release
  stat:
    path: "{{ project_root }}/current"
  register: current_symlink

- name: Set current release name or default
  set_fact:
    current_release: "{{ (current_symlink.stat.islnk | default(false)) | ternary(current_symlink.stat.lnk_target | basename, '00000000000000') }}"

- name: Release call to Levcharity Portal API
  uri:
    url: "https://portal.levcharity.com/api/v1/release"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      ip: "{{ ansible_host }}"
      url: "https://{{ site }}"
      releases: "{{ releases_array }}"
      current: "{{ current_release }}"
    status_code: 200,201,202,204
    timeout: 30
  register: api_result
  no_log: false
  retries: 3
  delay: 5

- name: Display API response (only in verbose mode)
  debug:
    var: api_result
    verbosity: 1